<?php
print '<!DOCTYPE html>';
print '<html lang="ja">';
print '<head>';
print '  <title>歴史チャットボットプロジェクト</title>';
print '  <meta charset="utf-8">';
print '  <meta name="viewport" content="width=device-width, initial-scale=1">';
print '  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">';
print '  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>';
print '  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>';
print '  <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>';
print '</head>';
print '<body>';
print '<nav class="navbar navbar-inverse">';
print '  <div class="navbar-header">';
print '    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnav">';
print '      <span class="icon-bar"></span>';
print '      <span class="icon-bar"></span>';
print '      <span class="icon-bar"></span>';
print '    </button>';
print '  </div>';
print '  <div id="gnav" class="collapse navbar-collapse">';
print '    <ul class="nav navbar-nav">';
print '      <li><a href="index.php">Top</a></li>';
print '      <li class="dropdown">';
print '        <a href="#" class="dropdown-toggle" data-toggle="dropdown">利用方法<span class="caret"></span></a>';
print '        <ul class="dropdown-menu">';
print '          <li><a href="mention.php">メンション形式</a></li>';
print '        </ul>';
print '      </li>';
print '      <li class="dropdown">';
print '        <a href="#" class="dropdown-toggle" data-toggle="dropdown">参考文献<span class="caret"></span></a>';
print '        <ul class="dropdown-menu">';
print '          <li><a href="resources.php">情報源</a></li>';
print '          <li class="divider"></li>';
print '          <li><a href="contact.php">連絡先</a></li>';
print '          <li class="divider"></li>';
print '          <li><a href="paper.php">論文</a></li>';
print '        </ul>';
print '      </li>';
print '      <li><a href="../index.php"><img src="./figs/united-kingdom-flag-round-icon-32.png" alt=""></a></li>';
print '      <li><a href="./index.php"><img src="./figs/japan-flag-round-icon-32.png" alt=""></a></li>';
print '      <li><a href="https://mobile.twitter.com/HistoChatbot"><img src="./figs/twitter.png" alt=""></a></li>';
print '    </ul>';
print '  </div>';
print '</nav>';
print '<div class="container">';
?>
